#!/bin/bash

# Cloudflare Nameserver Change Script
# Instructions for manual configuration

echo "=== CLOUDFLARE NAMESERVER CHANGE ==="
echo ""
echo "1. Open Chrome and go to:"
echo "   https://dash.cloudflare.com/login"
echo ""
echo "2. Log in to your Cloudflare account"
echo ""
echo "3. Select domain: islacuriosa.com"
echo ""
echo "4. Click on 'DNS' from the left menu"
echo ""
echo "5. Look for 'Custom nameservers' or 'Advanced' section"
echo ""
echo "6. Enter these nameservers:"
echo "   ns1.vercel-dns.com"
echo "   ns2.vercel-dns.com"
echo ""
echo "7. Click Save/Continue"
echo ""
echo "8. Wait for DNS propagation (24-48 hours)"
echo ""
echo "=== VERIFICATION ==="
echo "After changing, verify with:"
echo "dig +short NS islacuriosa.com"
echo ""
echo "=== CURRENT STATUS ==="
echo "Vercel deployment:"
echo "https://islacuriosa-r7t2m2rdm-nadalpiantini-fcbc2d66.vercel.app"
echo ""
echo "=== DONE ==="